name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 11.8.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^7.0.6
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_vector_icons: ^2.0.0
  path_provider: ^2.1.4
  dotted_border: ^2.1.0

  #Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  firebase_pagination: ^4.0.1
  firebase_messaging: ^15.1.3

  flutter_local_notifications: ^17.2.3
  flutter_html: ^3.0.0-beta.2
  flutter_custom_tabs: ^2.1.0
  syncfusion_flutter_charts: ^27.1.52
  geocoding: ^3.0.0
  webview_flutter: ^4.9.0
  country_picker: ^2.0.26

  #image:
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  file_picker: ^8.1.2
  lottie: ^3.1.2

  # PAYMENTS
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main  
  phonepe_payment_sdk: ^2.0.3
  flutter_stripe: ^11.2.0
  razorpay_flutter: ^1.3.7
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main

  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.1.0

  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  custom_map_markers: ^0.0.2+1
  permission_handler: ^11.3.1
  share_plus: ^10.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/upi_payment/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
